platform :ios, '9.0'

target 'CounterDemo' do
  use_frameworks!

  pod 'ReactorKit', '~> 1.1.0'
  pod 'RxSwift', '~> 4.0.0'
  pod 'RxCocoa', '~> 4.0.0'
  
  
end

target 'CounterDemoTests' do
    use_frameworks!
    pod 'ReactorKit', '~> 1.1.0'
    pod 'RxBlocking', '~> 4.0'
    pod 'RxTest',     '~> 4.0'
    pod 'RxExpect'
end

target 'CounterDemoUITests' do
    use_frameworks!
    pod 'ReactorKit', '~> 1.1.0'
    pod 'RxBlocking', '~> 4.0'
    pod 'RxTest',     '~> 4.0'
    pod 'RxExpect'

end

