platform :ios, '9.0'

target 'CounterDemo' do
  use_frameworks!

  pod 'ReactorKit', '~> 1.1.0'
  pod 'RxSwift', '~> 4.0.0'
  pod 'RxCocoa', '~> 4.0.0'
  
  
end

target 'CounterDemoTests' do
    use_frameworks!
    pod 'ReactorKit', '~> 1.1.0'

end

target 'CounterDemoUITests' do
    use_frameworks!
    pod 'ReactorKit', '~> 1.1.0'

end

