# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Joke' do
  	# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  	use_frameworks!

  	# Pods for Joke
	pod 'Alamofire'
	pod 'Kingfisher'
	pod 'SwiftyJSON'
    pod 'HandyJSON', '4.0.0-beta.1'
    
    target 'JokeTests' do
        inherit! :search_paths
        # Pods for testing
    end
    
    target 'JokeUITests' do
        inherit! :search_paths
        # Pods for testing
    end
end
