# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Joke' do
  	# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  	use_frameworks!

  	# Pods for Joke
    pod 'Alamofire'                 # 网络请求框架
    pod 'Moya', '~> 10.0'           # 网络请求框架
    pod 'Kingfisher'                # 图片加载
    pod 'SwiftyJSON'                # Json解析
    pod 'HandyJSON', '4.0.0-beta.1' # Json <-> Model
    pod 'XCGLogger', '~> 6.0.2'     # 日志框架
    pod 'SnapKit'                   # 代码布局
    pod 'R.swift'                   # 优雅使用资源文件
    
    pod 'RxSwift', '~> 4.0'
    pod 'RxCocoa', '~> 4.0'
    pod 'RxDataSources'
    
end

target 'JokeTests' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    # Pods for testing
    # RxTests and RxBlocking make the most sense in the context of unit/integration tests
    pod 'RxBlocking', '~> 4.0'
    pod 'RxTest',     '~> 4.0'
end

target 'JokeUITests' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    # Pods for testing
end
