# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Joke' do
  	# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  	use_frameworks!

  	# Pods for Joke
    pod 'Alamofire'                 # 网络请求框架
    pod 'Moya', '~> 10.0'           # 网络请求框架
    pod 'Kingfisher'                # 图片加载
    pod 'SwiftyJSON'                # Json解析
    pod 'HandyJSON', '4.0.0-beta.1' # Json <-> Model
    pod 'XCGLogger', '~> 6.0.2'     # 日志框架
    pod 'SnapKit'                   # 代码布局
    pod 'R.swift'                   # 优雅使用资源文件
    
    target 'JokeTests' do
        inherit! :search_paths
        # Pods for testing
    end
    
    target 'JokeUITests' do
        inherit! :search_paths
        # Pods for testing
    end
end
