platform :ios, '9.0'

target 'RxTodo' do
  use_frameworks!

  # Architecture
  pod 'ReactorKit'

  # Rx
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod 'RxOptional'
  pod 'RxViewController'

  # UI
  pod 'SnapKit'
  pod 'ManualLayout'

  # Misc.
  pod 'Then'
  pod 'ReusableKit'
  pod 'CGFloatLiteral'
  pod 'URLNavigator'

  # Testing
  target 'RxTodoTests' do
    pod 'RxTest'
    pod 'RxExpect'
    pod 'RxOptional'
  end

end
