# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Joke-Moya' do
  	# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  	use_frameworks!

  	# Pods for Joke
    pod 'Alamofire', '~> 4.6.0'     # 网络请求框架
    pod 'Moya', '~> 10.0'           # 网络请求框架
    pod 'Moya/RxSwift'
    pod 'Kingfisher', '~>4.6.1'     # 图片加载
    pod 'SwiftyJSON', '~>4.0.0'     # Json解析
    pod 'ObjectMapper', '~> 3.1.0'  # Json解析
    pod 'HandyJSON', '4.0.0-beta.1' # Json <-> Model
    pod 'XCGLogger', '~> 6.0.2'     # 日志框架
    pod 'SnapKit', '~> 4.0.0'       # 代码布局
    pod 'R.swift', '~> 4.0.0'       # 优雅使用资源文件
    pod 'Then', '~>2.3.0'
    
    pod 'RxSwift', '~> 4.0'
    pod 'RxCocoa', '~> 4.0'
    pod 'RxDataSources', '~> 3.0.2'
    pod 'NSObject+Rx', '~> 4.2.0'

  target 'Joke-MoyaTests' do
    inherit! :search_paths

    # Pods for testing
    pod 'RxBlocking', '~> 4.0'
    pod 'RxTest',     '~> 4.0'
  end

  target 'Joke-MoyaUITests' do
    inherit! :search_paths
    # Pods for testing
    
  end
    
end
